# This workflow is used to build and publish the snap to the store on every push to main.
name: CICD

on:
  push:
    branches:
      - main

  workflow_dispatch: # manual trigger


# Keep one CICD run active at a time so publish/test/promote happen in order
concurrency:
  group: ${{ github.workflow }}
  queue: max

jobs:
  cicd:
    if: github.repository == 'canonical/nomic-embed-text-v1.5-snap' # do not run on forks
    uses: canonical/inference-snaps-dev/.github/workflows/reuse-cicd.yaml@v2
    with:
      build-runner: |
        [
          "ubuntu-latest",
          "ubuntu-24.04-arm"
        ]
      build-init-script: 'download-models.sh'
      store-track: latest
      snap-name: nomic-embed-text-v1-5
      smoke-test-engine: cpu
